import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <script src="https://apis.google.com/js/platform.js" async defer></script>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="google-signin-client_id" content="YOUR_CLIENT_ID">
          <script>
            function onSignIn(googleUser) {
              const id_token = googleUser.getAuthResponse().id_token;
              fetch('/api/authenticate', {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json'
                },
                body: JSON.stringify({id_token})
              })
              .then(response => {
                if (response.ok) {
                  window.location.href = '/dashboard';
                } else {
                  alert('Authentication failed. Please try again.');
                }
              });
            }
          </script>
        </meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <h1>Google Drive API</h1>
        <div className="g-signin2" data-onsuccess="onSignIn">
            Hello
        </div>
      </body>
    </>
  )
}
